# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calories Consumed', models.IntegerField(verbose_name='Calories consumed or explled during this activity.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('E', 'Eaten'), ('X', 'Exercise')], default='E', max_length=1)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logged Weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight at the time the entry was created.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log_date', models.DateField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
